### ISSUE TITLE
NoneType is not iterable

### ISSUE THREAD

**Issue by jabberabbe** [Dionach/CMSmap#13]
When i use cmsmap, i get this error:
 cmsmap Traceback (most recent call last):   File "./cmsmap.py", line 2008, in <module>     bruter.Start()   File "./cmsmap.py", line 1249, in Start     self.WPXMLRPC_brute()   File "./cmsmap.py", line 1265, in WPXMLRPC_brute     for pwd in self.pswlist: TypeError: 'NoneType' object is not iterable

**Comment by thezakman** [comment]
Same here.
