### ISSUE TITLE
Exception in thread while scanning joomla components

### ISSUE THREAD

**Issue by Xneos128** [Dionach/CMSmap#2]
System: Kali linux 1.1.0a (uname -r: 3.18.0-kali1-amd64) on virtualbox (2cpu, 2gb ram)
Python 2.7.3 
gcc 4.7.2
Arguments used: ./cmsmap.py -f J -F -T 3 -v -o log.txt -t http://somesite/dir
Screenshot:
![screenshot 2015-03-30 08 40 40](https://cloud.githubusercontent.com/assets/890902/6891282/5afd5b4e-d6b9-11e4-865b-5ceae1bda479.png)

**Comment by m7x** [comment]
have you tried to re-clone the project? It seems you are using an old version.

**Comment by Xneos128** [comment]
Ok I've re-cloned the project and tried this time without updating joomla ( -U J ) but it happened again:

![screenshot 2015-03-30 13 51 39](https://cloud.githubusercontent.com/assets/890902/6895773/f6388db6-d6e3-11e4-9889-daccce467873.png)

(Sorry for the screenshot but I can't copy-paste)

**Comment by m7x** [comment]
Try to reduce the number of threads. I have the impression that you scanning a very slow website.

**Comment by Xneos128** [comment]
I've tried scanning with only 1 tread and it gave me the same error... I even tried to run this scan from a CentOS 7 VPS with 100mbit bandwidth but it always ended up with this Exception

**Comment by m7x** [comment]
Are you running a full scan (-F)?

**Comment by Xneos128** [comment]
Yes

**Comment by Xneos128** [comment]
But it gives this exception even when I don't use -F

**Comment by Xneos128** [comment]
tried without -o and -v and it stops at 55% this time ( I've also done -U J ):

# CMSmap/cmsmap.py -f J -T 1 -t http://www.somesite.it/dir
...
[-] Searching Joomla Components ...
55%Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "CMSmap/cmsmap.py", line 1217, in run
    if e.code != self.notExistingCode and len(e.read()) not in self.notValidLen : self.pluginsFound.append(plugin)
TypeError: argument of type 'int' is not iterable

**Comment by m7x** [comment]
are you using Python 2.7? I see python2.6 from your error message

**Comment by Xneos128** [comment]
I've updated to python 2.7 but nothing changed:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "./cmsmap.py", line 1219, in run
    if e.code != self.notExistingCode and len(e.read()) not in self.notValidLen : self.pluginsFound.append(plugin)
TypeError: argument of type 'int' is not iterable

dirs3arch works fine

**Comment by dauchua** [comment]
i have the same problem when scan with joomla site : 

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "./cmsmap.py", line 1219, in run
    if e.code != self.notExistingCode and len(e.read()) not in self.notValidLen : self.pluginsFound.append(plugin)
TypeError: argument of type 'int' is not iterable

**Comment by dauchua** [comment]
I dont understand code so much but i change this code at line 829 from: 

for u in range(self.thread_num):           t=ThreadScanner(self.url,self.pluginPath,"/",self.pluginsFound,self.notExistingCode,self.notExistingCode,q)
            t.daemon = True
            t.start()

instead of : 

for u in range(self.thread_num):
            t = ThreadScanner(self.url,self.pluginPath,"/",self.pluginsFound,self.notExistingCode,self.notValidLen,q)
            t.daemon = True
            t.start()

it work like a charm :+1:

**Comment by athecat** [comment]
Similar problem, resolved opposite to the preceding comment
[-] Searching Joomla Components ...
96%Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "cmsmap.py", line 1219, in run
    if e.code != self.notExistingCode and len(e.read()) not in self.notValidLen : self.pluginsFound.append(plugin)
TypeError: argument of type 'int' is not iterable

code modified:
            t = ThreadScanner(self.url,self.pluginPath,"/",self.pluginsFound,self.notExistingCode,self.notValidLen,q)
