### ISSUE TITLE
[ERROR] CMS detection failed

### ISSUE THREAD

**Issue by nareshlamgade** [Dionach/CMSmap#26]
[ERROR] CMS detection failed :(
[ERROR] Use -f to force CMSmap to scan (W)ordpress, (J)oomla or (D)rupal

It's not able to detect Wordpress CMS 

I am running version 4.1.1

Is there any problem while detecting the newest version ?

**Comment by m7x** [comment]
it worked fine by me
```
$ ./cmsmap.py -t http://192.168.71.133/wp4
[-] Date & Time: 03/03/2015 23:46:50
[-] Target: http://192.168.71.133/wp4
[M] Website Not in HTTPS: http://192.168.71.133/wp4
[I] Server: Apache/2.2.22 (Debian)
[I] X-Powered-By: PHP/5.4.4-14+deb7u8
[L] X-Frame-Options: Not Enforced
[I] Strict-Transport-Security: Not Enforced
[I] X-Content-Security-Policy: Not Enforced
[I] CMS Detection: Wordpress
[I] Wordpress Version: 4.1.1
```
You can force CMSmap to do a Wordpress scan with the option ```-f W```

**Comment by m7x** [comment]
Hi. I will delete this repo and create a new one to make it lighter. I will invite you to clone the new repo.
