### ISSUE TITLE
404  pages

### ISSUE THREAD

**Issue by immauss** [Dionach/CMSmap#3]
When searching for certain files, such as settings.php on a Drupal site, the tool reports that it found all possibilities, but upon closer investigation, the pages returned were all 404 pages.

**Comment by m7x** [comment]
Can you please provide more info? OS and version of Python?

**Comment by immauss** [comment]
Yes,

    	It was on a CentOS 6.6 with python 2.6.6 


G.E. Scott Knauss
i <mailto:scott@knauss.com>mmauss@gmail.com
Computer Geek 
Security Guy
Linux Guru
