### ISSUE TITLE
local variable 'htmltext' referenced before assignment

### ISSUE THREAD

**Issue by rakeen09** [Dionach/CMSmap#30]
![image](https://cloud.githubusercontent.com/assets/10359412/6317753/079bf224-ba91-11e4-9bee-ed26e7a0d533.png)
![image](https://cloud.githubusercontent.com/assets/10359412/6317754/1ae5d4c6-ba91-11e4-90e4-8add74dccff9.png)

**Comment by cgreg21** [comment]
I have this error.

**Comment by m7x** [comment]
Hi. I will delete this repo and create a new one to make it lighter. I will invite you to clone the new repo.
