### ISSUE TITLE
Showing two different server for http and https

### ISSUE THREAD

**Issue by rakeen09** [Dionach/CMSmap#31]
Don't know if it is possible to have apache for https and nginx for http, but if it is not I hope you find this helpful

![image](https://cloud.githubusercontent.com/assets/10359412/6317776/1eaa04c2-ba93-11e4-8f95-6949d345a760.png)

**Comment by Trozz** [comment]
Hey Rakeen09

This is completely valid, you can have any number of web servers running on different ports.

**Comment by m7x** [comment]
Hi. I will delete this repo and create a new one to make it lighter. I will invite you to clone the new repo.
