### ISSUE TITLE
unknown error?

### ISSUE THREAD

**Issue by rakeen09** [Dionach/CMSmap#34]
![image](https://cloud.githubusercontent.com/assets/10359412/6429491/93216b26-bfff-11e4-8164-c1141dff07a7.png)

**Comment by pedrodj** [comment]
Hi rakeen,

which version of Perl you run under Windows ? Do you use Active Perl ?

Let me know ;)

**Comment by rakeen09** [comment]
I'm not sure I use perl at all :/
I've xampp installed and it has Perl v5.16.3   Other than that I use python2.7

btw, Does CMSmap require perl?!

**Comment by pedrodj** [comment]
Sorry my fault, I mean Python :)

I'm installing Xampp and trying cmsmap: let you know :)

**Comment by rakeen09** [comment]
wait, xampp doesn't include python afaik

**Comment by pedrodj** [comment]
Yes I know,

installing perl 2.7.9 ;)

**Comment by m7x** [comment]
Hi. I will delete this repo and create a new one to make it lighter. I will invite you to clone the new repo.
