### ISSUE TITLE
local variable 'htmltext' referenced before assignment

### ISSUE THREAD

**Issue by shayanb** [Dionach/CMSmap#38]
Just after running CMSmap.py on Mac OS X 10.10 Python 2.7.9 
(previous version of CMSmap worked fine)
```
Traceback (most recent call last):
  File "./cmsmap.py", line 1971, in <module>
    scanner.FindCMSType()
  File "./cmsmap.py", line 220, in FindCMSType
    if e.code == 403 and len(htmltext) not in self.notValidLen and not self.CMSFound:
UnboundLocalError: local variable 'htmltext' referenced before assignment
```

**Comment by thinkxl** [comment]
Same here

**Comment by giray** [comment]
+1

**Comment by handrij** [comment]
+2 Same error, is there a workaround???

**Comment by shayanb** [comment]
https://github.com/Dionach/CMSmap/pull/41 is a workaround for this issue, It solves this issue but I couldn't get good results from CMSmap. it always find the CMS as wordpress even on joomla.org

**Comment by m7x** [comment]
Hi. I will delete this repo and create a new one to make it lighter. I will invite you to clone the new repo.
