### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by jaikishantulswani** [dionach/CMSmap#5]
Hello,
It is still needed user input for update even after providing the -U flag. Can you please let me know whats the proper Flag to use.

**Comment by m7x** [comment]
Hello

`cmsmap.py -U C`  will update CMSmap. You can get the flags from CMSmap error message when you provide a not valid one:

```
cmsmap.py -U z
[-] Date & Time: 18/01/2019 15:31:42
[-] Not Valid Option Provided. Use (C)MSmap, (P)lugins or (PC) for both
[-] Example: cmsmap.py -U PC
```
or from the help menu:
```
  -U , --update         use (C)MSmap, (P)lugins or (PC) for both
```
